# Generated by Django 5.0.3 on 2024-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlokDef",
            fields=[
                (
                    "IdBlokDef",
                    models.AutoField(
                        db_column="IdBlokDef", primary_key=True, serialize=False
                    ),
                ),
                ("Jmeno", models.TextField()),
                ("Barva", models.TextField()),
            ],
            options={
                "db_table": "BlokDef",
            },
        ),
    ]
