# Generated by Django 5.0.3 on 2024-08-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlokDef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Jmeno", models.TextField()),
                ("Barva", models.TextField()),
            ],
            options={
                "db_table": "BlokDef",
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Time", models.DateTimeField()),
                ("CzkEur", models.FloatField()),
                ("cEle", models.FloatField()),
            ],
            options={
                "db_table": "Market",
                "unique_together": {("Time",)},
            },
        ),
        migrations.CreateModel(
            name="BlokVS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Time", models.DateTimeField()),
                ("Lin", models.FloatField()),
                ("Abs", models.FloatField()),
                (
                    "IdBlokDef",
                    models.ForeignKey(
                        db_column="IdBlokDef",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ampiatomigrations.blokdef",
                    ),
                ),
            ],
            options={
                "db_table": "BlokVS",
                "unique_together": {("IdBlokDef", "Time")},
            },
        ),
        migrations.CreateModel(
            name="BlokVykon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Time", models.DateTimeField()),
                ("pInst", models.FloatField()),
                ("pDos", models.FloatField()),
                ("pMin", models.FloatField()),
                (
                    "IdBlokDef",
                    models.ForeignKey(
                        db_column="IdBlokDef",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ampiatomigrations.blokdef",
                    ),
                ),
            ],
            options={
                "db_table": "BlokVykon",
                "unique_together": {("IdBlokDef", "Time")},
            },
        ),
    ]
