# Generated by Django 5.0.3 on 2024-08-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ampiatomigrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlokOmezeni",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Time", models.DateTimeField()),
                ("ZmenaVykonu", models.FloatField()),
                (
                    "IdBlokDef",
                    models.ForeignKey(
                        db_column="IdBlokDef",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ampiatomigrations.blokdef",
                    ),
                ),
            ],
            options={
                "db_table": "BlokOmezeni",
                "unique_together": {("IdBlokDef", "Time")},
            },
        ),
    ]
