# Generated by Django 5.0.3 on 2024-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ampiatomigrations", "0002_market_blokvs_blokvykon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blokdef",
            name="IdBlokDef",
            field=models.BigAutoField(
                db_column="IdBlokDef", primary_key=True, serialize=False
            ),
        ),
    ]
