# Generated by Django 5.0.3 on 2024-08-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ampiatomigrations", "0002_blokomezeni"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlokOmezeni",
        ),
    ]
