# Generated by Django 5.0.3 on 2024-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ampiatomigrations", "0003_delete_blokomezeni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blokvs",
            name="Lin",
        ),
    ]
